### ISSUE TITLE
HACS tuki?

### ISSUE THREAD

**Issue by haivala** [carohauta/oma-helen-ha-integration#1]
https://hacs.xyz/docs/publish/start

**Comment by carohauta** [comment]
Hyvä idea 👍 En itse käytä HACSia niin ei tullut mieleen

Varmaan seuraavaksi vois toteuttaa nyt kun sain vihdoin tehtyä Helenin pörssisähköllekin tuen.

**Comment by carohauta** [comment]
HACS Custom -tuki löytyy. En ainakaan toistaiseksi näe syytä nostaa viralliselle HACS-listalle.
