### ISSUE TITLE
Multible contracts

### ISSUE THREAD

**Issue by thahacs** [carohauta/oma-helen-ha-integration#15]
If have multiple contracts look that integration return values from newest. Is there way to way to select contract e.g. using contract number?

**Comment by carohauta** [comment]
Hi!

At the moment there is no support for multiple contracts and it will always select the newest one. However, supporting multiple contracts is something that I am planning to include in future releases.

**Comment by Komentorivi** [comment]
Hope to get this soon 👍

**Comment by KurtMar** [comment]
Looks like Caro has updated the core CLI last night!
https://github.com/carohauta/oma-helen-cli/releases/tag/1.2.0

**Comment by carohauta** [comment]
Just pushed an update to the integration today. HACS seems to have picked it up immediately. 

So if you have multiple contracts with Helen, you can now provide a new configuration parameter for the integration: `delivery_site_id`. You can check for the wanted delivery site in Oma Helen. If the site id is not provided, the integration will default to the latest contract.

Let me know if there are any issues with it 👍

**Comment by djjassu** [comment]
I have a solar panels here and selling the energy to Helen. The solar plant has it's own delivery_site_id as the normal contract have its own.

Is it possible to get both graphs to HA? Does the script support multiple delivery_site_id's ?

**Comment by carohauta** [comment]
You can add the sensor as many times as you like so yes, you can have multiple sites' data in your HA. However, `energy-production` products are not (officially) supported at the moment so data about energy that you sell back to the grid might not display properly
