### ISSUE TITLE
1-2 measurements/day

### ISSUE THREAD

**Issue by Jese44** [carohauta/oma-helen-ha-integration#18]
Hi there! i was able to add the values to HA energy consumption tab (after struggling for unknown reason; system wouldn't get data from helen and/or calculate with nordpool integrations price but now it at least measures) but i've gotten max 2 values per day, i.e. 9.1. i got two measurements to energy tab; 18:00 and 21:00 (15,67 kWh and 26,18kWh) and by far on 10.1. (at 21:00) i have just one at 18:00 (15,39kWh).... does it work as intended or should I get measurements for every hour of a day (i know helen seems to report data for every hour on their website)? 10.1. was the first day without any struggles with HA or energy tab.
also something is not measured right; for 9.1. energy tab shows 41,85kWh as consumption whereas Helen shows 15,39kWh... Have i done smth wrong or is there a bug?
sensors i have: 
consumption: sensor.helen_monthly_consumption
used with entity with current price:
Nordpool_kwh_fi_eur_3_10_024
https://github.com/custom-components/nordpool/

**Comment by Jese44** [comment]
![image](https://github.com/carohauta/oma-helen-ha-integration/assets/45014337/07432b46-89ed-4134-97fe-73436195ee46)
![image](https://github.com/carohauta/oma-helen-ha-integration/assets/45014337/e5e1c723-3c62-4b59-b719-db4a5e43c90b)

**Comment by Jese44** [comment]
![image](https://github.com/carohauta/oma-helen-ha-integration/assets/45014337/b6dea5b9-5c39-42c2-9fac-348b6c0c3e2f)
Also all data shown in this (copypasted the code from your example) is correct.
HA data:
core 2024.1.2
supervisor: 2023.12.0
OS: 11.2
frontend:20240104.0

Nordpool current version.
Helen hacs integration version 51ba965
Exchange contract.

**Comment by golonac** [comment]
Same for me, it almost works with the energy dashboard but it has these differences compared to the Oma Helen dashboard:
- 1-2 measurements per day - maybe the default is one and server restarts do another measurement? Looked at the code and didn't notice anything related to scheduling except `SCAN_INTERVAL = timedelta(hours=3)`, changed to hours=1 but didn't notice any effect.
- The dates are off by one - Oma Helen shows consumption for e.g. 2024-01-01, but HA energy usage graph shows the same consumption for 2024-01-02.
- Sometimes part of one day's consumption is incorrectly marked for the next/prev day - e.g. in Oma Helen I have 133.32kWh on day 1 and 119.52 on day 2, but in HA energy dashboard I get 124.05 on day 1 and 128.79 on day 2 (disregarding the 1 day offset mentioned above) - both have the same total consumption for the 2 days, so in HA some of day 1's consumption has gone to day 2.

**Comment by carohauta** [comment]
Hi and thanks for the feedback!

The first problem is that Oma Helen is not a real time tracker. It usually only refreshes your data once per day and sometimes not even that often. When the data does get refreshed, HA inserts the new data into the energy consumption diagram and just assumes that the change was real time i.e. the timestamp which it inserts the data into is always current time.

The second problem is that the energy dashboard does not currently support inserting data in to past so there is no way to distribute the hourly data into the diagram with correct timestamps.

**Comment by golonac** [comment]
Ah that makes sense! I asked Helen's customer support if they're planning to add realtime data, but probably not. I suppose the addon could output yesterday's hourly values at the same hour today (like, output yesterday's 13:00 reading at 13:00 today, then yesterday's 14:00 reading at 14:00 today, etc) to get it to play with the HA graph better, but it's a bit hacky and has the 1 day offset.

**Comment by Jese44** [comment]
I see, thanks for the solution and reply. Hopefully it's possible to use data from your integration some day!
