### ISSUE TITLE
Problem with settings or the data?

### ISSUE THREAD

**Issue by djjassu** [carohauta/oma-helen-ha-integration#19]
Installed the addon yesterday. Using the exchange -model and correct id for the place is used. Also of course the username and password has been set.

However the data looks like this... 

![Screenshot 2024-02-29 at 8 19 40](https://github.com/carohauta/oma-helen-ha-integration/assets/152852285/85389a3d-c888-4525-811f-2294934a0a9a)

My monthly usage is 2000-3000 kWh and when checking the Helen app, or their site the usage is looking right. What I am missing here? Template is the one that is on the instructions page .

the id has been changed to xxxxxxxxxx here, in real conf it is set to my delivery_site_id
********

sensor:
  - platform: helen_energy
    username: !secret oma_helen_username
    password: !secret oma_helen_password
    vat: 0.24
    contract_type: EXCHANGE
    include_transfer_costs: False # optional boolean (True/False)
    delivery_site_id: xxxxxxxxxxxxx # optional delivery site id for when you have multiple contracts with Helen
  - platform: template
    sensors:
      helen_exchange_energy_consumption:
        friendly_name: "This month energy consumption"
        unit_of_measurement: "kWh"
        icon_template: mdi:lightning-bolt
        device_class: "energy"
        value_template: >
          {{ 0 if state_attr('sensor.helen_exchange_electricity', 'current_month_consumption') == None else state_attr('sensor.helen_exchange_electricity', 'current_month_consumption') | round() }}
      helen_exchange_energy_consumption_last_month:
        friendly_name: "Last month energy consumption"
        unit_of_measurement: "kWh"
        icon_template: mdi:lightning-bolt
        value_template: >
          {{ 0 if state_attr('sensor.helen_exchange_electricity', 'last_month_consumption') == None else state_attr('sensor.helen_exchange_electricity', 'last_month_consumption')| round() }}
      helen_exchange_energy_last_month_total_cost:
        friendly_name: "Last month energy cost"
        unit_of_measurement: "e"
        icon_template: mdi:currency-eur
        value_template: >
            {{ 0 if state_attr('sensor.helen_exchange_electricity', 'last_month_total_cost') == None else state_attr('sensor.helen_exchange_electricity', 'last_month_total_cost') | round() }}
      helen_exchange_energy_daily_average_consumption:
        friendly_name: "Daily average consumption"
        unit_of_measurement: "kWh"
        icon_template: mdi:lightning-bolt
        value_template: >
          {{ 0 if state_attr('sensor.helen_exchange_electricity', 'daily_average_consumption') == None else state_attr('sensor.helen_exchange_electricity', 'daily_average_consumption') | round() }}

**Comment by djjassu** [comment]
Ok, it might be this :

***
This error originated from a custom integration.

Logger: root
Source: custom_components/helen_energy/sensor.py:183
Integration: helen_energy (documentation, issues)
First occurred: 08:56:02 (2 occurrences)
Last logged: 08:56:04

Cannot set '643007526006xxxxxx' because it does not exist in the active delivery sites list '[xxxxxxxx, yyyyyy]'
***

(the xxx and yyyy has set by me).

However the long number starting the 64300 is the correct id for the delivery site (checked multiple times in Helen contracts). Also used the set credentials for to check this.

could there be a problem to set the delivery_id ? I have 3 id's because of 2 house (1 has 2 id's because of the solar plant)

**Comment by carohauta** [comment]
Hi!

Helen products with domain `electricity-production` have purposefully been excluded from the contract list. Mainly because I don't have visibility in the data structure since I don't have solar panels (and therefore no `electricity-production` contracts myself). 

This is something I might be interested in developing in the future but at the moment I have not plans for it.

**Comment by djjassu** [comment]
> Hi!
> 
> Helen products with domain `electricity-production` have purposefully been excluded from the contract list. Mainly because I don't have visibility in the data structure since I don't have solar panels (and therefore no `electricity-production` contracts myself).
> 
> This is something I might be interested in developing in the future but at the moment I have not plans for it.

But the  id's for normal exchange deals should still work. The production has its own id and normal contract have its own.

Now even the normal contract is mot shown correctly.

**Comment by carohauta** [comment]
My delivery site id has only seven numbers. You should try with either one of those two numbers logged by the error since they are the only ones that will work.

It seems like the Helen login API has changed today so some new problems might pop up soon.

**Comment by djjassu** [comment]
> My delivery site id has only seven numbers. You should try with either one of those two numbers logged by the error since they are the only ones that will work.
> 
> It seems like the Helen login API has changed today so some new problems might pop up soon.

Those numbers are not working.

All my delivery site id's have 18 digits , also the one site that does not have solar. the seven numbers that are shown in the log, are not any part of my site id.

Site id's have been checked both from Helen and from the Distribution companys side. 18 digits.

Distribution companies are Vantaan Energia and Järvi-Suomen Energia .

**Comment by carohauta** [comment]
> Those numbers are not working.

Do you get a different error this time (when using one of the two shorter numbers)?

**Comment by djjassu** [comment]
> > Those numbers are not working.
> 
> Do you get a different error this time (when using one of the two shorter numbers)?

No errors, but data is "Unavailable" and other are zeros.

**Comment by carohauta** [comment]
Helen had changed their login API so the integration was actually broken for a couple of days. The issue has been fixed in version `1.3.1`.

About the delivery site id: it used to be a seven digit number which you could look up from your energy invoice or in Oma Helen, but they have since migrated into using an 18 digit GSRN number instead; that `64300xxx...` starting one. Peculiarly enough, they still use the seven digit number in the API for some reason.

Anyway, I amended the integration so that it now also accepts the 18 digit GSRN number in the `delivery_site_id` field in addition to the seven digit "old standard" number.

**Comment by djjassu** [comment]
Works now with the 18 digit site id. Thanks!
