### ISSUE TITLE
Siirtomaksut

### ISSUE THREAD

**Issue by haivala** [carohauta/oma-helen-ha-integration#3]
Saako sieltä tietoa mahdollisesti myös siirtomaksusta?

**Comment by carohauta** [comment]
Sopimus-APIn parametreissä on viitteitä siirtoon esim. 
```
GET https://api.omahelen.fi/v9/contract/list?include_transfer=true&update=true&include_products=true
```
Response ei kuitenkaan sisällä siirron hintatietoja. Siirtolasku tulee itselleni muualta, joten voi olla ettei niitä sen takia näy minulla Helenin palvelussa.

**Comment by haivala** [comment]
Eli todennäköisesti sieltä sais tuon tiedon..
On hämäävää että sitä ei nyt ole hinnoissa mukana.

**Comment by carohauta** [comment]
Laitan vielä tännekin, että uusi versio `1.1.0` tukee nyt myös siirtomaksuja, kun lisää konfiguraatioon uuden kentän `include_transfer_costs: True`.
