### ISSUE TITLE
Connecting to Väppi API?

### ISSUE THREAD

**Issue by FunctionalHacker** [carohauta/oma-helen-ha-integration#7]
Is Helen's API at all similar to the Väppi API? https://api.vappi.fi

I'm looking into getting electricity usage to my HA instance and found this. If there is any similarities I could use this add-on as a starting point.

**Comment by carohauta** [comment]
In the sense that it is a REST API, yeah there are some similarities.

I like the fact that they provide OAS3 compliant documentation for the API but it does not look complete to me. For example, it seems to be missing endpoints (and models) for getting consumption data. The Väppi app is not familiar to me but surely it provides energy consumption data, they just have not documented it.

Väre seems to have a portal for browsers too so perhaps you can find the energy consumption endpoints that way.

**Comment by FunctionalHacker** [comment]
Okay, thanks for the pointers. I guess In have some learning ahead of me.
